### ISSUE TITLE
Regression in handling of nested Objects

### ISSUE THREAD

**Issue by jbrunclik** [elastic/elasticsearch-dsl-py#477]
Hello,

we are currently migrating our ElasticSearch cluster from 1.x to 2.x and as part of this process we are upgrading `elasticsearch-dsl` from `0.x.x` to `2.x.x`.

We have noticed a regression in handling nested Objects between `0.0.11` and `2.1.0`.

To reproduce the issue I have created the following `DocType`:

``` python
class Provider(DocType):
    metadata = Object(
        properties={
            'help': Object(
                properties={
                    'afr': String(),
                    'eng': String(),
                }
            )
        }
    )
```

If you set the value of `metadata` at once, i.e. by calling:

``` python
provider1 = Provider()
provider1.metadata = {
    'help': {
        'afr': 'foo',
        'eng': 'bar',
    }
}
print provider1.to_dict()
```

Everything works as axpected:

``` python
{'metadata': {'help': {'afr': 'foo', 'eng': 'bar'}}}
```

However if you are building the `metadata` piece by piece, e.g.:

``` python
provider2 = Provider()
provider2.metadata = {}
provider2.metadata['help'] = {}
provider2.metadata['help']['afr'] = 'foo'
provider2.metadata['help']['eng'] = 'bar'
print provider2.to_dict()
```

You end up with `AttributeError`:

``` python
Traceback (most recent call last):
  File "./test.py", line 33, in <module>
    print provider2.to_dict()
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/document.py", line 245, in to_dict
    d = super(DocType, self).to_dict()
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 367, in to_dict
    v = f.serialize(v)
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 70, in serialize
    return self._serialize(data)
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 185, in _serialize
    return data.to_dict()
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/utils.py", line 367, in to_dict
    v = f.serialize(v)
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 70, in serialize
    return self._serialize(data)
  File "~/.virtualenvs/cms/lib/python2.7/site-packages/elasticsearch_dsl/field.py", line 185, in _serialize
    return data.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
```

The same code is working fine with `0.0.11`.

Is that something that should be fixed in `2.x.x` or is it backwards incompatible intentionally?

**Comment by HonzaKral** [comment]
Thanks for the report!

I am honestly not sure this should be fixed, what you should be doing (and what works) is:
```
provider2 = Provider()
provider2.metadata = {}
provider2.metadata.help = {}
provider2.metadata.help.afr = 'foo'
provider2.metadata.help.eng = 'bar'
print provider2.to_dict()
```

We intentionally don't interfere with the `['f']` assignment to allow for raw data access.

What do you think?

**Comment by jbrunclik** [comment]
> I am honestly not sure this should be fixed.

Thank you for the update. I am totally fine with that. I just wanted to make sure that the change of the behavior between the versions is not unintentional.
