### ISSUE TITLE
AttributeError in nested aggregations

### ISSUE THREAD

**Issue by pecheneff** [elastic/elasticsearch-dsl-py#648]
Hi, we've got a trouble with latest version of lib. Need help with that.

        s = search.index('db_index').doc_type('item')
        s.aggs.bucket('all', 'filter', filter=~Term(visibility=Product.VISIBILITY_HIDDEN))\
            .bucket('by_type', 'filters', filters={
                'active': Term(visibility=Product.VISIBILITY_VISIBLE) & 
                              Term(status=Product.STATUS_VERIFIED),
                'reserved': Term(visibility=Product.VISIBILITY_RESERVED),
                'moderated': Terms(status=[Product.STATUS_MODERATION_REQUIRED,
                                           Product.STATUS_MODERATION_STASHED]),
                'promoted': Range(**{'promotion.until': {'gte': timezone.now()}})
            })

        q = Bool(filter=[
            Term(user_id=request.user.id),
            Terms(status=[Product.STATUS_VERIFIED,
                          Product.STATUS_MODERATION_REQUIRED,
                          Product.STATUS_MODERATION_STASHED]),
            Terms(visibility=[Product.VISIBILITY_VISIBLE,
                              Product.VISIBILITY_RESERVED,
                              Product.VISIBILITY_HIDDEN])
        ])
        resp = s.query(q)[:0].execute()

        aggregated_data = {
            'active': resp.aggregations.all.by_type.buckets.active.doc_count,
            'promoted': resp.aggregations.all.by_type.buckets.promoted.doc_count,
            'moderated': resp.aggregations.all.by_type.buckets.moderated.doc_count,
            'reserved': resp.aggregations.all.by_type.buckets.reserved.doc_count,
        }

Code worked with 5.1.0 version, but doesn't with 5.2.0. Thanks for any help. Have a nice day.

Here some info from ipdb:

ipdb> resp
<Response: []>
ipdb> resp.aggregations
{u'active': {u'by_category': {u'buckets': [{u'key': 6, u'doc...}
ipdb> resp.aggregations.all
{u'by_type': {u'buckets': {u'active': {u'doc_count': 14}, u'...}
ipdb> resp.aggregations.all.by_type
{u'buckets': {u'active': {u'doc_count': 14}, u'reserved': {u...}
ipdb> resp.aggregations.all.by_type.buckets
[u'active', u'reserved', u'inactive', u'moderated', u'promoted']
ipdb> resp.aggregations.all.by_type.buckets.active
*** AttributeError: 'list' object has no attribute 'active'

**Comment by exslim** [comment]
@HonzaKral - Indeed, there is a bug with nested aggregations introduced in 5.2.0. You just can't access second level bucket via object attribute.
