### PR TITLE
Removed `__orig_class__` attribute out of AttrDict instances

### LINKED ISSUE #1876: v8.15.0 breaks things related to type hints?
Hello,

some of my existing code breaks when upgrading from v8.14.0 to v8.15.0 as follows:

```
self = elasticsearch_dsl.utils.AttrDict[typing.Any], attr = 'doc_count'

    def __getattr__(self, attr):
        if attr in {'__name__', '__qualname__'}:
            return self._name or self.__origin__.__name__

        # We are careful for copy and pickle.
        # Also for simplicity we don't relay any dunder names
        if '__origin__' in self.__dict__ and not _is_dunder(attr):
>           return getattr(self.__origin__, attr)
E           AttributeError: type object 'AttrDict' has no attribute 'doc_count'

/usr/lib/python3.12/typing.py:1185: AttributeError
```

Greetings,

jgb

### PR DESCRIPTION
**Pull request by miguelgrinberg**
Fixes #1876 

This change addressed a regression introduced in 8.15.0 as part of the refactor to support type hints.

The problem is in `AttrDict`, which can get confused and inject an attribute named `__orig_class__` in the underlying dict. For example:

```python
>>> from typing import Any
>>> from elasticsearch_dsl import AttrDict
>>> d = AttrDict[Any]({})
>>> d.to_dict()
{'__orig_class__': elasticsearch_dsl.utils.AttrDict[typing.Any]}
```

This happens because Python adds the `__orig_class__` attribute to all instances that were created with explicit generic arguments given. The logic in `AttrDict.__setattr__` to detect if an attribute is part of the dictionary or a real attribute of the instance does not work for `__orig_class__`.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
Thanks! LGTM. I see #1878 fixes the CI.
